stages:
  process_data:
    cmd: python3 src/process_data.py ${model_type}
    deps:
    - src/process_data.py
    - data/data.csv
    outs:
    - data/X_train.csv
    - data/X_valid.csv
    - data/X_test.csv
    - data/y_train.csv
    - data/y_valid.csv
    - data/y_test.csv

  train_model:
    cmd: python3 src/train_model.py ${model_type}
    deps:
    - src/train_model.py
    - data/X_train.csv
    - data/X_valid.csv
    - data/X_test.csv
    - data/y_train.csv
    - data/y_valid.csv
    - data/y_test.csv
    metrics:
    - metrics/metrics.json:
        cache: false


