name: churn-pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          
          dvc pull data/data.csv
          dvc repro 

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add figure to the report
          echo "## Validating results"
          cml-publish figures/metrics.png --md >> report.md
          cml-send-comment report.md
